import type { CampusEvent } from "./types";

/**
 * Dummy events for UCSB / IV area. Replace with API fetch when backend is ready.
 * Coordinates are approximate for campus and Isla Vista locations.
 */
function isoAtLocalTime(daysFromNow: number, hour24: number, minute = 0): string {
  const now = new Date();
  const date = new Date(
    now.getFullYear(),
    now.getMonth(),
    now.getDate() + daysFromNow,
    hour24,
    minute,
    0,
    0,
  );
  return date.toISOString();
}

function isoPlusHours(startIso: string, hours: number): string {
  const d = new Date(startIso);
  d.setHours(d.getHours() + hours);
  return d.toISOString();
}

export const DUMMY_EVENTS: CampusEvent[] = [
  {
    id: "1",
    name: "IV Block Party",
    position: [34.4132, -119.8612],
    startTime: isoAtLocalTime(3, 18, 0),
    endTime: isoAtLocalTime(3, 23, 0),
    location: "Del Playa Drive, Isla Vista",
    category: "Social",
    subtype: "Block party",
    foodProvided: "free",
    freeAdmission: true,
    rsvpLink: "https://example.com/iv-block-party",
  },
  {
    id: "2",
    name: "CoE Tech Talk: AI in Research",
    position: [34.4142, -119.8428],
    startTime: isoAtLocalTime(1, 14, 0),
    endTime: isoAtLocalTime(1, 15, 30),
    location: "Harold Frank Hall 1104",
    category: "Academic",
    subtype: "CoE",
    foodProvided: null,
    freeAdmission: true,
    sourceLink: "https://example.com/coe-events",
  },
  {
    id: "3",
    name: "Study Group — Math 4A",
    position: [34.4125, -119.8482],
    startTime: isoAtLocalTime(0, 10, 0),
    endTime: isoAtLocalTime(0, 12, 0),
    location: "Library Room 1312",
    category: "Academic",
    subtype: "Study group",
    foodProvided: null,
    freeAdmission: true,
  },
  {
    id: "4",
    name: "Mens' Basketball vs Rival",
    position: [34.4155, -119.8495],
    startTime: isoAtLocalTime(6, 19, 0),
    endTime: isoAtLocalTime(6, 21, 0),
    location: "Thunderdome",
    category: "Sports",
    subtype: "Mens' Basketball",
    foodProvided: "costs-extra",
    freeAdmission: false,
    rsvpLink: "https://example.com/gaucho-tickets",
  },
  {
    id: "5",
    name: "Film Screening: Documentary Night",
    position: [34.4138, -119.8472],
    startTime: isoAtLocalTime(2, 19, 30),
    endTime: isoAtLocalTime(2, 21, 30),
    location: "IV Theater",
    category: "Entertainment",
    subtype: "Film screening",
    foodProvided: "free",
    freeAdmission: true,
    sourceLink: "https://example.com/iv-theater",
  },
  {
    id: "6",
    name: "Laid-back Beach Volleyball",
    position: [34.4088, -119.865],
    startTime: isoAtLocalTime(4, 15, 0),
    endTime: isoAtLocalTime(4, 17, 0),
    location: "Campus Point",
    category: "Social",
    subtype: "Laid-back",
    foodProvided: null,
    freeAdmission: true,
  },
  {
    id: "7",
    name: "Band Performance — Campus Band",
    position: [34.414, -119.8489],
    startTime: isoAtLocalTime(8, 20, 0),
    endTime: isoAtLocalTime(8, 22, 0),
    location: "Storke Plaza",
    category: "Entertainment",
    subtype: "Band performance",
    foodProvided: "costs-extra",
    freeAdmission: true,
    rsvpLink: "https://example.com/campus-band",
  },
  {
    id: "8",
    name: "Professor Talk: Climate Science",
    position: [34.4132, -119.8418],
    startTime: isoAtLocalTime(12, 16, 0),
    endTime: isoAtLocalTime(12, 17, 30),
    location: "Bren Hall 1414",
    category: "Academic",
    subtype: "Professor Talk",
    foodProvided: "free",
    freeAdmission: true,
  },
  {
    id: "9",
    name: "Baseball — Gauchos vs Fullerton",
    position: [34.4162, -119.8512],
    startTime: isoAtLocalTime(20, 14, 0),
    endTime: isoAtLocalTime(20, 17, 0),
    location: "Caesar Uyesaka Stadium",
    category: "Sports",
    subtype: "Baseball",
    foodProvided: "costs-extra",
    freeAdmission: false,
    rsvpLink: "https://example.com/baseball-tickets",
  },
  {
    id: "10",
    name: "Theater Play: Spring Production",
    position: [34.4148, -119.8455],
    startTime: isoAtLocalTime(27, 19, 0),
    endTime: isoAtLocalTime(27, 21, 30),
    location: "Hatlen Theater",
    category: "Entertainment",
    subtype: "Theater Play",
    foodProvided: null,
    freeAdmission: false,
    sourceLink: "https://example.com/theater",
  },
  {
    id: "11",
    name: "Career Fair Prep: Resume Review",
    position: [34.4141, -119.8459],
    startTime: isoAtLocalTime(9, 12, 0),
    endTime: isoPlusHours(isoAtLocalTime(9, 12, 0), 2),
    location: "SRB Lobby",
    category: "Academic",
    subtype: "CoLS",
    foodProvided: null,
    freeAdmission: true,
  },
  {
    id: "12",
    name: "Sunset Picnic + Games",
    position: [34.4109, -119.8588],
    startTime: isoAtLocalTime(15, 17, 30),
    endTime: isoPlusHours(isoAtLocalTime(15, 17, 30), 2),
    location: "Anisq'Oyo' Park",
    category: "Social",
    subtype: "Laid-back",
    foodProvided: "free",
    freeAdmission: true,
  },
];
